# Generated by Django 5.0.2 on 2024-10-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_personmodel_options_alter_profilemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='RoleModel',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLOYEE', 'Empleado'), ('VIEWER', 'Vista')], default='VIEWER', max_length=8),
        ),
    ]
