# Generated by Django 5.0.2 on 2024-11-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_options_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLOYEE', 'Empleado'), ('VIEWER', 'Vista')], default='VIEWER', max_length=8),
        ),
    ]
