# Generated by Django 5.0.2 on 2024-09-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_single_use',
            field=models.BooleanField(default=False),
        ),
    ]
