# Generated by Django 5.0.2 on 2024-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_categorymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransactionmodel',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venta'), ('LOST', 'Perdido'), ('DAMAGED', 'Dañado'), ('LOAN', 'Préstamo')], default='LOAN', max_length=8),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='unit',
            field=models.CharField(choices=[('GAL', 'Galón'), ('PC', 'Pieza'), ('BOX', 'Caja'), ('M', 'Metro'), ('L', 'Litro'), ('KG', 'Kilogramo'), ('PKG', 'Paquete')], default='PC', max_length=8),
        ),
    ]
