# Generated by Django 5.0.2 on 2024-11-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorytransactionmodel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransactionmodel',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('RETURN', 'Devolución'), ('SALE', 'Venta'), ('LOST', 'Perdido'), ('DAMAGED', 'Dañado'), ('LOAN', 'Préstamo')], default='LOAN', max_length=8),
        ),
    ]
