# Generated by Django 5.0.2 on 2024-11-16 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorytransactionmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.locationmodel', verbose_name='ubicación'),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.productmodel', verbose_name='producto'),
        ),
    ]
